#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Renders zoo.cfg from the environment, writes the myid file, then runs the
# requested role in the foreground.
#
# Roles:
#   server  ZooKeeper itself (default)
#   cli     zkCli.sh against this node
#   <other> executed verbatim, so `docker run ... bash` still works
#
# Environment (all have defaults from the Dockerfile):
#   ZOO_MY_ID           this node's id; must match its entry in ZOO_SERVERS
#   ZOO_SERVERS         space-separated ensemble, official-image format:
#                       "server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181"
#                       Leave empty for a standalone node.
#   ZOO_CLIENT_PORT / ZOO_TICK_TIME / ZOO_INIT_LIMIT / ZOO_SYNC_LIMIT
#   ZOO_DATA_DIR / ZOO_DATA_LOG_DIR
#   ZOO_4LW_COMMANDS_WHITELIST   four-letter words allowed (healthchecks use srvr)
#   ZOO_EXTRA_CONFIG    newline-separated extra zoo.cfg lines
# ---------------------------------------------------------------------------
set -euo pipefail

ROLE="${1:-server}"
CONFIG="${ZOOKEEPER_HOME}/conf/zoo.cfg"

render_config() {
  mkdir -p "${ZOO_DATA_DIR}" "${ZOO_DATA_LOG_DIR}"

  cat > "${CONFIG}" <<EOF
# Generated by entrypoint.sh on container start — edits here do not survive a
# restart. Change the environment instead.
dataDir=${ZOO_DATA_DIR}
dataLogDir=${ZOO_DATA_LOG_DIR}
clientPort=${ZOO_CLIENT_PORT}
clientPortAddress=0.0.0.0
tickTime=${ZOO_TICK_TIME}
initLimit=${ZOO_INIT_LIMIT}
syncLimit=${ZOO_SYNC_LIMIT}
maxClientCnxns=0
autopurge.snapRetainCount=5
autopurge.purgeInterval=24
4lw.commands.whitelist=${ZOO_4LW_COMMANDS_WHITELIST}
admin.enableServer=false
EOF

  # The ensemble. A single node with no ZOO_SERVERS runs standalone, which is
  # useful for a one-off `docker run` but not for this platform.
  if [[ -n "${ZOO_SERVERS:-}" ]]; then
    for server in ${ZOO_SERVERS}; do
      echo "${server}" >> "${CONFIG}"
    done
  fi

  if [[ -n "${ZOO_EXTRA_CONFIG:-}" ]]; then
    printf '%s\n' "${ZOO_EXTRA_CONFIG}" >> "${CONFIG}"
  fi

  # myid identifies this node within the ensemble; without it a clustered node
  # refuses to start.
  echo "${ZOO_MY_ID}" > "${ZOO_DATA_DIR}/myid"

  echo "--- ${CONFIG} ---"
  cat "${CONFIG}"
  echo "--- myid: $(cat "${ZOO_DATA_DIR}/myid") ---"
}

case "${ROLE}" in
  server)
    render_config
    # zkServer.sh start-foreground keeps the JVM in the foreground and logs to
    # stdout, which is what docker logs needs.
    exec "${ZOOKEEPER_HOME}/bin/zkServer.sh" --config "${ZOOKEEPER_HOME}/conf" start-foreground
    ;;
  cli)
    exec "${ZOOKEEPER_HOME}/bin/zkCli.sh" -server "localhost:${ZOO_CLIENT_PORT}"
    ;;
  *)
    exec "$@"
    ;;
esac
