#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Renders server.properties from KAFKA_* environment variables, then runs the
# requested role in the foreground.
#
# Roles:
#   broker   the Kafka broker (default)
#   init     create the topics listed in TOPICS, then exit (idempotent)
#   <other>  executed verbatim, e.g. `kafka-topics --list ...` or `bash`
#
# Every KAFKA_<NAME> variable becomes the property <name> with underscores
# turned into dots and the name lowercased:
#
#   KAFKA_BROKER_ID=1                 -> broker.id=1
#   KAFKA_ZOOKEEPER_CONNECT=zk:2181   -> zookeeper.connect=zk:2181
#   KAFKA_ADVERTISED_LISTENERS=...    -> advertised.listeners=...
#
# The control variables below are consumed by this script and never written to
# server.properties.
# ---------------------------------------------------------------------------
set -euo pipefail

ROLE="${1:-broker}"
CONFIG="${KAFKA_HOME}/config/server.properties"

# Not broker properties: either they configure the JVM/this script, or they
# belong to the init role.
readonly CONTROL_VARS=(
  KAFKA_HOME KAFKA_HEAP_OPTS KAFKA_OPTS KAFKA_JVM_PERFORMANCE_OPTS
  KAFKA_LOG4J_OPTS KAFKA_GC_LOG_OPTS KAFKA_JMX_OPTS KAFKA_ROLE
  KAFKA_VERSION KAFKA_SCALA_VERSION KAFKA_TOPICS KAFKA_TOPIC_PARTITIONS
  KAFKA_TOPIC_REPLICATION KAFKA_BOOTSTRAP
)

is_control_var() {
  local candidate="$1" control
  for control in "${CONTROL_VARS[@]}"; do
    [[ "${candidate}" == "${control}" ]] && return 0
  done
  return 1
}

render_config() {
  mkdir -p "${KAFKA_LOG_DIRS}"

  {
    echo "# Generated by entrypoint.sh on container start from KAFKA_* env vars."
    echo "# Edits here do not survive a restart; change the environment instead."
  } > "${CONFIG}"

  local name property
  # compgen lists the names of the exported variables, so values containing
  # spaces or '=' survive intact.
  for name in $(compgen -e | grep '^KAFKA_' | sort); do
    is_control_var "${name}" && continue
    property="$(echo "${name#KAFKA_}" | tr '[:upper:]_' '[:lower:].')"
    echo "${property}=${!name}" >> "${CONFIG}"
  done

  echo "--- ${CONFIG} ---"
  cat "${CONFIG}"
}

wait_for_broker() {
  local bootstrap="${KAFKA_BOOTSTRAP:-localhost:9092}" attempt
  for attempt in $(seq 1 60); do
    if kafka-broker-api-versions.sh --bootstrap-server "${bootstrap}" >/dev/null 2>&1; then
      return 0
    fi
    echo "waiting for ${bootstrap} to answer (${attempt}/60)..."
    sleep 3
  done
  echo "broker at ${bootstrap} never became reachable" >&2
  return 1
}

wait_for_broker_registration_slot() {
  local broker_id="${KAFKA_BROKER_ID:-}" connect="${KAFKA_ZOOKEEPER_CONNECT:-}" attempt output
  [[ -n "${broker_id}" && -n "${connect}" ]] || return 0
  for attempt in $(seq 1 60); do
    output="$(printf 'get /brokers/ids/%s\n' "${broker_id}" \
      | "${KAFKA_HOME}/bin/zookeeper-shell.sh" "${connect}" 2>&1 || true)"
    if grep -Fq "Node does not exist" <<<"${output}"; then
      return 0
    fi
    if grep -Fq '"broker.id"' <<<"${output}" || grep -Fq '"endpoints"' <<<"${output}"; then
      echo "waiting for stale ZooKeeper broker registration ${broker_id} to expire (${attempt}/60)..."
    else
      echo "waiting for ZooKeeper broker registry (${attempt}/60)..."
    fi
    sleep 2
  done
  echo "ZooKeeper broker registration /brokers/ids/${broker_id} was not released" >&2
  return 1
}

case "${ROLE}" in
  broker)
    # Docker may stop ZooKeeper before a broker's session-close handshake is
    # persisted. On an immediate restart, starting Kafka while its old
    # ephemeral /brokers/ids/<id> node exists makes Kafka exit fatally and
    # Compose fails its dependencies. Wait for session expiry without deleting
    # a registration that could still belong to a live broker.
    wait_for_broker_registration_slot
    render_config
    exec "${KAFKA_HOME}/bin/kafka-server-start.sh" "${CONFIG}"
    ;;

  init)
    bootstrap="${KAFKA_BOOTSTRAP:-localhost:9092}"
    partitions="${KAFKA_TOPIC_PARTITIONS:-12}"
    replication="${KAFKA_TOPIC_REPLICATION:-3}"
    wait_for_broker
    for topic in ${KAFKA_TOPICS//,/ }; do
      echo "ensuring topic '${topic}' (${partitions} partitions, rf ${replication})"
      kafka-topics.sh --bootstrap-server "${bootstrap}" --create --if-not-exists \
        --topic "${topic}" --partitions "${partitions}" --replication-factor "${replication}"
    done
    echo "--- topics ---"
    exec kafka-topics.sh --bootstrap-server "${bootstrap}" --list
    ;;

  *)
    exec "$@"
    ;;
esac
